server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**

        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/article-service/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  public-get-paths: /article-service/api/articles
  public-post-paths: /auth-service/api/auth/register,/auth-service/api/auth/login
รณ