server:
  port: 8084

spring:
  application:
    name: statistics-service

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: com.doroz.events

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

feign:
  client:
    config:
      default:
        request-interceptors:
          - com.doroz.statistics_service.client.FeignAuthInterceptor