server:
  port: 8084

spring:
  application:
    name: statistics-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

feign:
  client:
    config:
      default:
        request-interceptors:
          - com.doroz.statistics.interceptor.FeignAuthInterceptor

